compute_environment: LOCAL_MACHINE
enable_cpu_affinity: false
debug: false
downcast_bf16: 'no'
# distributed_type: MULTI_GPU
# gpu_ids: '0,1'
# machine_rank: 1
# num_processes: 2
distributed_type: NO
gpu_ids: '0'
machine_rank: 0
num_processes: 1
num_machines: 1
main_training_function: main
mixed_precision: fp16
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
main_process_port: 29502
